[build]
  base = "final_html"
  command = "npm run build"
  publish = "final_html/dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
